//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerUI.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Team_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Team_Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackerUI.Resources.Team.Resource", typeof(Team_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Cellphone.
        /// </summary>
        internal static string CellphonePlaceholder {
            get {
                return ResourceManager.GetString("CellphonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Email.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter First Name.
        /// </summary>
        internal static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to fill in all of the fields..
        /// </summary>
        internal static string InvalidInformation {
            get {
                return ResourceManager.GetString("InvalidInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Last Name.
        /// </summary>
        internal static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose Team Member.
        /// </summary>
        internal static string MemberPlaceholder {
            get {
                return ResourceManager.GetString("MemberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not available members..
        /// </summary>
        internal static string NotExistMembers {
            get {
                return ResourceManager.GetString("NotExistMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Team Name.
        /// </summary>
        internal static string TeamNamePlaceholder {
            get {
                return ResourceManager.GetString("TeamNamePlaceholder", resourceCulture);
            }
        }
    }
}
